/**
 * Single source of truth for all Local Lead Engine site content.
 * Specialized in Google Ads Management for Local Service Contractors.
 */

export const images = {
  heroPortrait:
    'https://ik.imagekit.io/Localleadengine/profile%20picture.png?updatedAt=1777916935270',
  cafeCall:
    'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80',
  twoMen:
    'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
  teamDesk:
    'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
  coworking:
    'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=80',
  presenting:
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
  deskFlat:
    'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1200&q=80',
  bedroomDesk:
    'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
  twoLaptops:
    'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80',
} as const;

export type NavItem = {
  label: string;
  href: string;
  children?: { label: string; href: string }[];
};

export const navItems: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'Services', href: '/services' },
  { label: 'Case Study', href: '/case-studies' },
  { label: 'About Us', href: '/about' },
  { label: 'Contact Us', href: '/contact' },
];

export const aiFeatures = [
  {
    icon: 'Megaphone',
    title: 'Google Ads Management',
    body: 'Hyper-targeted Google Search & Local Services Ads (LSA) campaigns built exclusively for local service contractors to generate qualified estimate requests.',
  },
  {
    icon: 'BarChart3',
    title: 'Conversion Tracking',
    body: 'Complete phone and form attribution connecting Google Ads to CallRail and CRM to track exact booked jobs and ROAS.',
  },
  {
    icon: 'Smartphone',
    title: 'Landing Page Design',
    body: 'High-speed, custom mobile contractor landing pages engineered to convert clicks into high-margin calls and booked estimate requests.',
  },
] as const;

export const marqueeLogos = [
  { name: 'HubSpot', logo: 'https://ik.imagekit.io/Localleadengine/HubSpot%20Logo.png' },
  { name: 'Google Tag Manager', logo: 'https://ik.imagekit.io/Localleadengine/Google%20Tag%20Manager%20Logo.png' },
  { name: 'Zapier', logo: 'https://ik.imagekit.io/Localleadengine/Zapier%20Logo.png' },
  { name: 'Google Ads', logo: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20Logo.png' },
  { name: 'Google Analytics', logo: 'https://ik.imagekit.io/Localleadengine/Google%20Analytics%20Logo.png' },
  { name: 'ServiceTitan', logo: 'https://ik.imagekit.io/Localleadengine/ServiceTitan%20Logo.png' },
  { name: 'GoHighLevel', logo: 'https://ik.imagekit.io/Localleadengine/Go%20High%20Level%20Logo.png' },
  { name: 'CallRail', logo: 'https://ik.imagekit.io/Localleadengine/CallRail%20Logo.png' },
  { name: 'Jobber', logo: 'https://ik.imagekit.io/Localleadengine/Joober%20Logo.png' },
] as const;

export const growFeatures = [
  {
    icon: 'PhoneCall',
    title: 'Exclusive Live Phone Calls',
    body: 'Stop competing over shared leads. Every phone call generated by Local Lead Engine routes directly to your dispatchers.',
  },
  {
    icon: 'LayoutTemplate',
    title: '25%+ Conversion Landing Pages',
    body: 'High-speed mobile landing pages custom-engineered for HVAC, Roofing, Plumbing, and Electrical trade contractors.',
  },
] as const;

export const projectFilters = [
  'Show All',
  'HVAC',
  'Roofing',
  'Plumbing',
  'Electrical',
  'Restoration',
] as const;

export type Project = {
  id: string;
  title: string;
  category: string;
  tags: string[];
  image: string;
  summary: string;
  metric: string;
  metricLabel: string;
};

export const projects: Project[] = [
  {
    id: 'titan-hvac',
    title: 'Titan HVAC & Air Conditioning',
    category: 'HVAC',
    tags: ['HVAC', 'Search Ads'],
    image: images.teamDesk,
    summary:
      'Scaled monthly booked AC installation and emergency repair calls from 34 to 182 in 90 days while slashing cost-per-lead by 68%.',
    metric: '6.2x',
    metricLabel: 'Ad Spend ROAS',
  },
  {
    id: 'apex-roofing',
    title: 'Apex Roofing & Solar',
    category: 'Roofing',
    tags: ['Roofing', 'LSA'],
    image: images.coworking,
    summary:
      'Captured $420,000 in full roof replacement contracts in Q2 using hyper-targeted Google Search Ads and Local Services Ads.',
    metric: '142',
    metricLabel: 'Full Roof Replacement Leads',
  },
  {
    id: 'vanguard-plumbing',
    title: 'Vanguard Plumbing & Drain',
    category: 'Plumbing',
    tags: ['Plumbing', 'Search Ads'],
    image: images.presenting,
    summary:
      'Eliminated 42% of wasted ad spend in 30 days with a negative keyword guard while doubling 24/7 emergency drain cleaning calls.',
    metric: '$32.50',
    metricLabel: 'Average Cost Per Lead',
  },
  {
    id: 'premier-electric',
    title: 'Premier Electrical Services',
    category: 'Electrical',
    tags: ['Electrical', 'Landing Pages'],
    image: images.twoLaptops,
    summary:
      'Built a high-converting panel upgrade landing page that converted 28.4% of Google Ads clicks into direct booked phone appointments.',
    metric: '215',
    metricLabel: 'Booked Panel Upgrades',
  },
  {
    id: 'proclean-restoration',
    title: 'ProClean Water & Fire Restoration',
    category: 'Restoration',
    tags: ['Restoration', 'Search Ads'],
    image: images.deskFlat,
    summary:
      'Dominating 24/7 emergency water damage search queries across three major metro counties with instant click-to-call mobile ads.',
    metric: '78%',
    metricLabel: 'Call Conversion Rate',
  },
  {
    id: 'precision-paving',
    title: 'Precision Paving & Masonry',
    category: 'Plumbing',
    tags: ['Restoration', 'LSA'],
    image: images.bedroomDesk,
    summary:
      'Out-ranking national lead aggregators with hyper-local geo-fencing and automated Google LSA lead dispute management.',
    metric: '7.1x',
    metricLabel: 'Return on Ad Spend',
  },
];

export type Testimonial = {
  quote: string;
  name: string;
  role: string;
  rating: string;
  platform: string;
  score: number;
};

export const testimonials: Testimonial[] = [
  {
    quote:
      'Local Lead Engine turned our Google Ads around in less than 30 days. We went from burning $5,000/month on junk clicks to getting 65+ exclusive calls every single month for our HVAC business.',
    name: 'Marcus Vance',
    role: 'Owner, Vance Heating & Air',
    rating: '5.0/5',
    platform: 'Google Reviews',
    score: 98,
  },
  {
    quote:
      'Our previous agency kept bragging about "impressions" and "clicks". Local Lead Engine actually tracks booked jobs inside ServiceTitan. Our return on ad spend is over 6x now!',
    name: 'Sarah Jenkins',
    role: 'Operations Director, Apex Roofing',
    rating: '4.9/5',
    platform: 'Clutch Contractor Review',
    score: 96,
  },
  {
    quote:
      'The Local Services Ads (LSA) setup alone was worth every dollar. We got our Google Screened badge and high-ticket plumbing leads started coming directly to our dispatch board.',
    name: 'Dave Kowalski',
    role: 'Founder, Kowalski Plumbing & Drain',
    rating: '5.0/5',
    platform: 'Google Partner Verified',
    score: 99,
  },
];

export type PlanFeatureRow = {
  name: string;
  starter: boolean;
  growth: boolean;
  scale: boolean;
};

export type Plan = {
  id: string;
  name: string;
  blurb: string;
  featured?: boolean;
};

export const plans: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    blurb: 'Essential search ad management and foundational tracking for local contractors.',
  },
  {
    id: 'growth',
    name: 'Growth',
    blurb: 'Advanced tracking, call attribution, and dashboard reporting for growing contractors.',
    featured: true,
  },
  {
    id: 'scale',
    name: 'Scale',
    blurb: 'Full landing page design, priority support, and complete campaign management.',
  },
];

export const planFeatureRows: PlanFeatureRow[] = [
  { name: 'Google Ads Management', starter: true, growth: true, scale: true },
  { name: 'Google Local Services Ads', starter: false, growth: true, scale: true },
  { name: 'Conversion Tracking Setup', starter: true, growth: true, scale: true },
  { name: 'Google Analytics 4 Setup', starter: true, growth: true, scale: true },
  { name: 'Google Tag Manager Setup', starter: true, growth: true, scale: true },
  { name: 'Automation Setup', starter: true, growth: true, scale: true },
  { name: 'Monthly Reporting', starter: true, growth: true, scale: true },
  { name: 'Landing Page Recommendations', starter: true, growth: true, scale: true },
  { name: 'Landing Page Design', starter: false, growth: false, scale: true },
  { name: 'Offline Conversion Tracking Setup', starter: false, growth: true, scale: true },
  { name: 'Call Tracking Integration', starter: false, growth: true, scale: true },
  { name: 'Looker Studio Dashboard', starter: false, growth: true, scale: true },
  { name: 'A/B Testing', starter: false, growth: true, scale: true },
  { name: 'Priority Support', starter: false, growth: false, scale: true },
];

export type Post = {
  id: string;
  title: string;
  category: string;
  date: string;
  day: string;
  month: string;
  author: string;
  image: string;
  excerpt: string;
  readTime: string;
};

export const posts: Post[] = [
  {
    id: 'stop-wasting-ad-budget',
    title: 'How Contractors Can Stop Wasting Google Ads Budget on DIYers',
    category: 'Google Ads Strategy',
    date: '12 July 2026',
    day: '12',
    month: 'Jul',
    author: 'Marcus Vance',
    image: images.deskFlat,
    excerpt:
      'Search terms like "free repair guide", "DIY wiring", and "jobs" drain thousands from contractor ad budgets. Here are 120 negative keywords every HVAC and roofing business needs.',
    readTime: '6 min read',
  },
  {
    id: 'search-vs-lsa',
    title: 'Google Search Ads vs. LSA: Which Generates Cheaper Calls?',
    category: 'LSA Insights',
    date: '28 June 2026',
    day: '28',
    month: 'Jun',
    author: 'Sarah Jenkins',
    image: images.bedroomDesk,
    excerpt:
      'Local Services Ads offer pay-per-call leads, while Search Ads allow custom landing pages. Here is how top-performing contractors combine both for maximum ROI.',
    readTime: '5 min read',
  },
  {
    id: 'contractor-landing-page-guide',
    title: 'The Anatomy of a Contractor Landing Page That Converts at 25%+',
    category: 'Conversion Optimization',
    date: '15 June 2026',
    day: '15',
    month: 'Jun',
    author: 'Dave Kowalski',
    image: images.twoLaptops,
    excerpt:
      'Most contractor websites fail because they look like brochure sites. Learn the 7 layout triggers that convert mobile visitors into immediate phone calls.',
    readTime: '8 min read',
  },
  {
    id: 'disputing-invalid-lsa-leads',
    title: 'How to Dispute Invalid Google LSA Phone Leads for Full Refunds',
    category: 'LSA Insights',
    date: '02 June 2026',
    day: '02',
    month: 'Jun',
    author: 'Marcus Vance',
    image: images.teamDesk,
    excerpt:
      'Wrong service area? Out of scope? Spam calls? Step-by-step framework for recovering thousands in refund credits directly from Google Local Services Ads.',
    readTime: '4 min read',
  },
  {
    id: 'servicetitan-jobber-attribution',
    title: 'Tracking Real ROAS: Connecting Google Ads to ServiceTitan & Jobber',
    category: 'Analytics & CRM',
    date: '20 May 2026',
    day: '20',
    month: 'May',
    author: 'Sarah Jenkins',
    image: images.coworking,
    excerpt:
      'Stop judging campaigns by click counts. How to trace a Google search query directly to a completed $8,500 HVAC replacement inside your dispatch software.',
    readTime: '7 min read',
  },
];

export const services = [
  {
    icon: 'Megaphone',
    title: 'Google Ads Management',
    body: 'Hyper-targeted Google Search & Local Services Ads (LSA) campaigns built exclusively for local service contractors to generate qualified estimate requests.',
    points: ['High-intent keyword structuring', 'Negative keyword filtering', 'Local Services Ads (LSA) management'],
  },
  {
    icon: 'BarChart3',
    title: 'Conversion Tracking',
    body: 'Complete phone and form attribution connecting Google Ads to CallRail and CRM to track exact booked jobs and ROAS.',
    points: ['CallRail call recording and DNI setup', 'ServiceTitan and Jobber CRM sync', 'Revenue and ROAS reporting'],
  },
  {
    icon: 'Smartphone',
    title: 'Landing Page Design',
    body: 'High-speed, custom mobile contractor landing pages engineered to convert clicks into high-margin calls and booked estimate requests.',
    points: ['High lead conversion design', 'Mobile-first speed optimization', 'Instant CRM form and call routing'],
  },
] as const;

export const stats = [
  { value: 100, suffix: '+', label: 'Contractor campaigns managed' },
  { value: 100, suffix: 'K+', label: 'Leads generated' },
  { value: 98, suffix: '%', label: 'Contractor retention rate' },
  { value: 8, suffix: 'x', label: 'Average Return on Ad Spend (ROAS)' },
] as const;

/* ------------------------------------------------------------------ */
/* Live Results — anonymised rolling contractor campaign benchmark   */
/* ------------------------------------------------------------------ */

export type ResultsTab = {
  id: string;
  label: string;
  icon: string;
  kind: 'line' | 'bar';
  format: 'k' | 'pct' | 'int' | 'decimal';
  title: string;
  headline: string;
  headlineLabel: string;
  delta: string;
  note: string;
  labels: string[];
  series: { name: string; color: string; values: number[]; dashed?: boolean }[];
  kpis: { label: string; value: string; hint: string }[];
};

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export const resultsTabs: ResultsTab[] = [
  {
    id: 'leads',
    label: 'Exclusive Phone Leads',
    icon: 'PhoneCall',
    kind: 'line',
    format: 'int',
    title: 'Monthly qualified phone leads, rolling 12 months',
    headline: '1,420',
    headlineLabel: 'Booked phone leads last month',
    delta: '+340% year on year',
    note: 'Blended across active HVAC, Roofing, Plumbing, and Electrical campaigns. Exclusive inbound calls from ready-to-hire local homeowners.',
    labels: MONTHS,
    series: [
      {
        name: 'Total phone calls',
        color: '#0052FF',
        values: [320, 380, 450, 590, 720, 880, 990, 1120, 1210, 1310, 1380, 1420],
      },
      {
        name: 'Form quote requests',
        color: '#0A0F1D',
        values: [110, 140, 180, 230, 290, 340, 390, 440, 480, 510, 540, 580],
        dashed: true,
      },
    ],
    kpis: [
      { label: 'Call answer rate', value: '94%', hint: 'direct to dispatcher' },
      { label: 'Avg call duration', value: '4m 12s', hint: 'high buying intent' },
      { label: 'Booked job rate', value: '68%', hint: 'from call to dispatch' },
    ],
  },
  {
    id: 'cpl',
    label: 'Cost Per Lead (CPL)',
    icon: 'DollarSign',
    kind: 'bar',
    format: 'int',
    title: 'Average Cost Per Lead ($) by trade category',
    headline: '$38.50',
    headlineLabel: 'Average CPL across all trades',
    delta: '-62% vs agency average',
    note: 'By combining Google Search Ads with Local Services Ads and tight negative keyword guards, we consistently cut contractor cost per lead by over 60%.',
    labels: ['HVAC', 'Plumbing', 'Roofing', 'Electrical', 'Restoration', 'Landscaping', 'Pest Control', 'Solar'],
    series: [
      {
        name: 'Local Lead Engine CPL',
        color: '#0052FF',
        values: [36, 32, 58, 29, 64, 28, 24, 72],
      },
      {
        name: 'Industry Average CPL',
        color: '#0A0F1D',
        values: [110, 95, 165, 85, 180, 75, 68, 190],
      },
    ],
    kpis: [
      { label: 'HVAC Cost/Lead', value: '$36.00', hint: 'down from $110' },
      { label: 'Roofing Cost/Lead', value: '$58.00', hint: 'down from $165' },
      { label: 'Plumbing Cost/Lead', value: '$32.00', hint: 'down from $95' },
    ],
  },
  {
    id: 'roas',
    label: 'Return on Ad Spend (ROAS)',
    icon: 'TrendingUp',
    kind: 'line',
    format: 'decimal',
    title: 'Monthly Return on Ad Spend (ROAS) multiplier',
    headline: '5.8x',
    headlineLabel: 'Average ROAS across client accounts',
    delta: '$5.80 returned per $1 ad spend',
    note: 'Tracked directly through ServiceTitan and Jobber integrations. Every dollar invested in Google Ads yields measurable booked service revenue.',
    labels: MONTHS,
    series: [
      {
        name: 'Client Account ROAS',
        color: '#0052FF',
        values: [2.1, 2.4, 2.9, 3.4, 3.8, 4.2, 4.6, 5.0, 5.2, 5.5, 5.7, 5.8],
      },
      {
        name: 'Target Threshold',
        color: '#0A0F1D',
        values: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0],
        dashed: true,
      },
    ],
    kpis: [
      { label: 'Monthly ad revenue', value: '$3.2M+', hint: 'tracked in CRM' },
      { label: 'Avg ticket size', value: '$2,450', hint: 'installations & repairs' },
      { label: 'Payback period', value: '< 14 days', hint: 'from ad click to job cash' },
    ],
  },
];

export const processSteps = [
  {
    step: '01',
    title: 'Phase 1 - Audit & Implement',
    body: 'We audit your account, fix tracking, and build the foundation for accurate measurement.',
  },
  {
    step: '02',
    title: 'Phase 2 - Launch',
    body: 'We launch high-intent Google Ads campaigns designed to generate qualified estimate requests.',
  },
  {
    step: '03',
    title: 'Phase 3 - Optimize',
    body: 'We improve lead quality, reduce wasted ad spend, and optimize for booked estimates.',
  },
  {
    step: '04',
    title: 'Phase 4 - Scale',
    body: 'We increase budget strategically, expand winning campaigns, and drive sustainable growth.',
  },
] as const;

export const team = [
  { name: 'Marcus Vance', role: 'Founder & CEO' },
  { name: 'Sarah Jenkins', role: 'Head of Google Ads Strategy' },
  { name: 'Dave Kowalski', role: 'Director of Contractor Growth' },
  { name: 'Priya Raman', role: 'Lead Landing Page Engineer' },
  { name: 'Tomas Lindqvist', role: 'Click Fraud & LSA Specialist' },
  { name: 'Élodie Marchand', role: 'CRM Attribution Specialist' },
] as const;

export const openRoles = [
  { title: 'Senior Google Ads Strategist (Contractor Focus)', type: 'Full time', place: 'Remote / US' },
  { title: 'Contractor Landing Page Designer', type: 'Full time', place: 'Remote' },
  { title: 'Local Services Ads (LSA) Manager', type: 'Full time', place: 'Remote' },
  { title: 'ServiceTitan & CRM Integration Engineer', type: 'Contract', place: 'Remote' },
] as const;

export const faqs = [
  {
    q: 'How quickly will phone calls start coming in?',
    a: 'Google Ads Search and LSA campaigns go live within 5 to 7 business days following onboarding. Inbound calls usually start within hours of campaign launch.',
  },
  {
    q: 'What makes our approach different for contractors?',
    a: 'We specialize in local service contractors in plumbing, HVAC, roofing, and electrical trades. Instead of reporting impressions or raw clicks, we measure phone calls, booked appointments, and total job revenue.',
  },
  {
    q: 'Who pays for the Google Ad spend?',
    a: 'You pay Google directly through your own Google Ads account. We manage and optimize your account for a flat monthly fee.',
  },
  {
    q: 'Do you require long-term contracts?',
    a: 'No, we operate on month-to-month agreements with clear communication and regular updates.',
  },
] as const;

export const footerColumns = [
  {
    title: 'Navigation',
    links: [
      { label: 'Home', href: '/' },
      { label: 'Services', href: '/services' },
      { label: 'Case Study', href: '/case-studies' },
      { label: 'About Us', href: '/about' },
      { label: 'Contact Us', href: '/contact' },
    ],
  },
  {
    title: 'Services',
    links: [
      { label: 'Google Search Ads', href: '/services' },
      { label: 'Local Services Ads (LSA)', href: '/services' },
      { label: 'Contractor Landing Pages', href: '/services' },
      { label: 'Click Fraud Shield', href: '/services' },
    ],
  },
  {
    title: 'Company',
    links: [
      { label: 'About Us', href: '/about' },
      { label: 'Case Studies', href: '/case-studies' },
      { label: 'Contractor Careers', href: '/about#careers' },
      { label: 'Book Strategy Call', href: '/contact' },
    ],
  },
] as const;

export const contactDetails = {
  address: ['350 Fifth Avenue, Suite 4800', 'New York, NY 10118'],
  email: 'hello@localleadengine.com',
  phone: '(800) 582-1940',
  hours: 'Mon – Fri, 7:00 AM – 6:00 PM EST',
};
