/**
 * Single source of truth for all Local Lead Engine site content.
 * Specialized in Google Ads Management for Local Service Contractors.
 */

export const images = {
  heroPortrait:
    'https://ik.imagekit.io/Localleadengine/profile%20picture.png?updatedAt=1777916935270',
  cafeCall:
    'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80',
  twoMen:
    'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
  teamDesk:
    'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
  coworking:
    'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=80',
  presenting:
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
  deskFlat:
    'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1200&q=80',
  bedroomDesk:
    'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
  twoLaptops:
    'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80',
} as const;

export type NavItem = {
  label: string;
  href: string;
  children?: { label: string; href: string }[];
};

export const navItems: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'Services', href: '/google-ads-for-local-service-contractors' },
  {
    label: 'Categories',
    href: '/google-ads-for-local-service-contractors',
    children: [
      { label: 'Roofing Contractors', href: '/contractors/google-ads-for-roofing-contractors' },
      { label: 'HVAC Contractors', href: '/contractors/google-ads-for-hvac-contractors' },
      { label: 'Home Remodeling Contractors', href: '/contractors/google-ads-for-remodeling-contractors' },
      { label: 'Window & Door Contractors', href: '/contractors/google-ads-for-window-door-contractors' },
      { label: 'Deck & Outdoor Living', href: '/contractors/google-ads-for-deck-outdoor-living-contractors' },
      { label: 'Solar Contractors', href: '/contractors/google-ads-for-solar-contractors' },
    ],
  },
  { label: 'Case Study', href: '/case-studies' },
  { label: 'About Us', href: '/about' },
  { label: 'Contact Us', href: '/contact' },
];

export const aiFeatures = [
  {
    icon: 'Megaphone',
    title: 'Google Ads Management',
    body: 'Hyper-targeted Google Search & Local Services Ads (LSA) campaigns built exclusively for local service contractors to generate qualified estimate requests.',
  },
  {
    icon: 'BarChart3',
    title: 'Conversion Tracking',
    body: 'Complete phone and form attribution connecting Google Ads to CallRail and CRM to track exact booked jobs and ROAS.',
  },
  {
    icon: 'Smartphone',
    title: 'Landing Page Design',
    body: 'High-speed, custom mobile contractor landing pages engineered to convert clicks into high-margin calls and booked estimate requests.',
  },
] as const;

export const marqueeLogos = [
  { name: 'HubSpot', logo: 'https://ik.imagekit.io/Localleadengine/HubSpot%20Logo.png' },
  { name: 'Google Tag Manager', logo: 'https://ik.imagekit.io/Localleadengine/Google%20Tag%20Manager%20Logo.png' },
  { name: 'Zapier', logo: 'https://ik.imagekit.io/Localleadengine/Zapier%20Logo.png' },
  { name: 'Google Ads', logo: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20Logo.png' },
  { name: 'Google Analytics', logo: 'https://ik.imagekit.io/Localleadengine/Google%20Analytics%20Logo.png' },
  { name: 'ServiceTitan', logo: 'https://ik.imagekit.io/Localleadengine/ServiceTitan%20Logo.png' },
  { name: 'GoHighLevel', logo: 'https://ik.imagekit.io/Localleadengine/Go%20High%20Level%20Logo.png' },
  { name: 'CallRail', logo: 'https://ik.imagekit.io/Localleadengine/CallRail%20Logo.png' },
  { name: 'Jobber', logo: 'https://ik.imagekit.io/Localleadengine/Joober%20Logo.png' },
] as const;

export const growFeatures = [
  {
    icon: 'PhoneCall',
    title: 'Exclusive Live Phone Calls',
    body: 'Stop competing over shared leads. Every phone call generated by Local Lead Engine routes directly to your dispatchers.',
  },
  {
    icon: 'LayoutTemplate',
    title: '25%+ Conversion Landing Pages',
    body: 'High-speed mobile landing pages custom-engineered for HVAC, Roofing, Plumbing, and Electrical contractors.',
  },
] as const;

export const projectFilters = [
  'Show All',
  'HVAC',
  'Roofing',
  'Home Remodeling',
  'Decks, Patios & Outdoor Living',
  'Window & Door',
  'Solar',
] as const;

export type Project = {
  id: string;
  title: string;
  category: string;
  tradeSlug?: string;
  tags: string[];
  image: string;
  summary: string;
  metric: string;
  metricLabel: string;
  location?: string;
  timeframe?: string;
  challenge?: string;
  solution?: string[];
  resultsList?: { label: string; value: string }[];
  clientQuote?: { quote: string; author: string; title: string };
};

export const projects: Project[] = [
  {
    id: 'nc-heating-air',
    title: 'NC Heating & Air',
    category: 'HVAC',
    tradeSlug: 'hvac',
    tags: ['HVAC', 'Search Ads', 'Call Tracking'],
    image: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20for%20HVAC%20Contractors.png',
    summary:
      'Scaled monthly booked AC replacement and emergency repair calls from 34 to 182 in 90 days while slashing cost-per-lead by 68%.',
    metric: '6.2x',
    metricLabel: 'Ad Spend ROAS',
    location: 'Raleigh-Durham, NC',
    timeframe: '90 Days',
    challenge:
      'NC Heating & Air was spending $8,000/month on generic Google Ads campaigns that brought low-margin tune-up calls and shared leads.',
    solution: [
      'Built a high-converting mobile-first landing page with direct click-to-call dispatch buttons.',
      'Implemented aggressive negative keyword lists blocking DIY and cheap repair search terms.',
      'Configured weather-triggered dynamic bid adjustments for heatwave surges.',
      'Synced call tracking with ServiceTitan to track exact closed jobs per ad campaign.',
    ],
    resultsList: [
      { label: 'Monthly Booked Calls', value: '182 Calls' },
      { label: 'Cost Per Booked Lead', value: '$68.50' },
      { label: 'Booked Replacement Jobs', value: '38 Completed Jobs' },
    ],
    clientQuote: {
      quote:
        'Local Lead Engine completely transformed our dispatch queue. We stopped buying shared leads and now run 100% on our own high-intent Google Ads call volume.',
      author: 'Marcus Vance',
      title: 'Owner, NC Heating & Air',
    },
  },
  {
    id: 'paragon-roofing',
    title: 'Paragon Roofing',
    category: 'Roofing',
    tradeSlug: 'roofing',
    tags: ['Roofing', 'Search Ads', 'LSA'],
    image: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20for%20Roofing%20Contractors?updatedAt=1786700490544',
    summary:
      'Captured 38 full roof replacement contracts in Q2 using storm-surge bidding and high-intent local search ads.',
    metric: '142',
    metricLabel: 'Full Replacement Leads',
    location: 'Dallas-Fort Worth, TX',
    timeframe: '120 Days',
    challenge:
      'High competitor CPCs were eating up ad budgets, and generic traffic was wasting money on minor patch repairs instead of full roof replacements.',
    solution: [
      'Created landing pages highlighting GAF Master Elite credentials and financing options.',
      'Optimized Google Local Services Ads (LSA) alongside Search Ads for maximum top-of-page real estate.',
      'Integrated CRM tracking to auto-pause campaigns in non-profitable postal codes.',
    ],
    resultsList: [
      { label: 'Full Roof Swaps Booked', value: '38 Jobs' },
      { label: 'Qualified Inbound Leads', value: '142 Leads' },
      { label: 'Pipeline ROAS', value: '7.8x' },
    ],
    clientQuote: {
      quote:
        'We booked 38 full roof replacements in four months. The quality of calls coming in is unmatched.',
      author: 'David Miller',
      title: 'Founder, Paragon Roofing',
    },
  },
  {
    id: 'home-repair-service',
    title: 'Home Repair Service',
    category: 'Home Remodeling',
    tradeSlug: 'remodeling',
    tags: ['Home Remodeling', 'Landing Pages', 'High-Ticket'],
    image: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20for%20Home%20Remodeling%20Contractors?updatedAt=1786700511856',
    summary:
      'Shifted focus from low-budget handyman repairs to exclusive kitchen & master bathroom design-build consultations.',
    metric: '18.4%',
    metricLabel: 'Form Conversion Rate',
    location: 'Denver, CO',
    timeframe: '60 Days',
    challenge:
      'Inundated with calls for tiny repairs and quick fixes, consuming team bandwidth without generating high-ticket design jobs.',
    solution: [
      'Engineered multi-step pre-qualification forms with mandatory project scope selection.',
      'Targeted high median-income zip codes across the metro area.',
      'Built an interactive project showcase displaying 3D renderings and customer video testimonials.',
    ],
    resultsList: [
      { label: 'Qualified Consultations', value: '46 Leads' },
      { label: 'Form Conversion Rate', value: '18.4%' },
      { label: 'Signed Design Contracts', value: '18 Remodel Jobs' },
    ],
    clientQuote: {
      quote:
        'Every lead that books through our new page knows our price range and is ready for a serious design consultation. Night and day difference.',
      author: 'Elena Rostova',
      title: 'Owner, Home Repair Service',
    },
  },
  {
    id: 'hoover-deck-porch',
    title: 'Hoover Deck & Porch',
    category: 'Decks, Patios & Outdoor Living',
    tradeSlug: 'deck-patio-outdoor-living',
    tags: ['Decks, Patios & Outdoor Living', 'Decks', 'LSA'],
    image: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20for%20Deck%20&%20Outdoor%20Living%20Contractors.png',
    summary:
      'Filled entire spring and summer custom composite deck, porch, and patio construction schedule in under 45 days.',
    metric: '210',
    metricLabel: 'Custom Deck Inquiries',
    location: 'Birmingham, AL',
    timeframe: '45 Days',
    challenge:
      'Slow winter lead volume created seasonal cash flow gaps and delayed spring project scheduling.',
    solution: [
      'Launched pre-season composite deck & porch campaign in early February with Google Search & LSA.',
      'Showcased custom outdoor kitchens, pergolas, screened porches, and fire pit upgrades.',
      'Offered early booking price locks for spring installation dates.',
    ],
    resultsList: [
      { label: 'Signed Deck & Porch Contracts', value: '28 Projects' },
      { label: 'Average Job Value', value: '$24,500' },
      { label: 'Schedule Capacity', value: '100% Booked' },
    ],
    clientQuote: {
      quote:
        'Our entire 6-month deck & porch installation queue was filled before spring even officially started. Incredible results.',
      author: 'Jason Cole',
      title: 'Founder, Hoover Deck & Porch',
    },
  },
  {
    id: 'universal-windows-direct-charlotte',
    title: 'Universal Windows Direct of Charlotte',
    category: 'Window & Door',
    tradeSlug: 'windows-doors',
    tags: ['Window & Door', 'Search Ads', 'Landing Pages'],
    image: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20for%20Window%20&%20Door%20Contractors?updatedAt=1786700619760',
    summary:
      'Booked 86 full-house window & custom door replacement consultations with high-converting mobile campaigns.',
    metric: '24.2%',
    metricLabel: 'Click-to-Call Rate',
    location: 'Charlotte, NC',
    timeframe: '90 Days',
    challenge:
      'Wasting budget on single broken glass repair requests rather than profitable 5+ window replacement & door projects.',
    solution: [
      'Excluded all glass repair terms and targeted 5+ window package and custom door replacement keywords.',
      'Highlighted energy efficiency savings, lifetime warranty benefits, and financing options.',
      'Offered an instant online measurement scheduling tool on the mobile landing page.',
    ],
    resultsList: [
      { label: 'In-Home Consults', value: '86 Consults' },
      { label: 'Average Order Value', value: '$18,400' },
      { label: 'Ad Spend ROAS', value: '6.9x' },
    ],
    clientQuote: {
      quote:
        'Local Lead Engine helped us dominate window and door replacement searches in Charlotte. The return on investment is undeniable.',
      author: 'Carlos Mendez',
      title: 'Owner, Universal Windows Direct of Charlotte',
    },
  },
  {
    id: 'california-solar-electric',
    title: 'California Solar & Electric Inc.',
    category: 'Solar',
    tradeSlug: 'solar',
    tags: ['Solar', 'Clean Energy', 'Search Ads'],
    image: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20for%20Solar%20Contractors.png',
    summary:
      'Replaced generic lead brokers with exclusive local residential solar and battery storage Google Ads leads.',
    metric: '5.5x',
    metricLabel: 'ROAS on Solar Installs',
    location: 'San Diego, CA',
    timeframe: '6 Months',
    challenge:
      'Paying high fees per lead to third-party brokers who resold the exact same homeowner lead to 4 competing solar companies.',
    solution: [
      'Designed local solar tax credit & utility rebate calculator landing page.',
      'Bypassed shared lead portals with direct 1-on-1 phone calls and site audit bookings.',
      'Filtered out homes with electric bills under $150/mo to ensure project viability.',
    ],
    resultsList: [
      { label: 'Exclusive Solar Leads', value: '94 Leads' },
      { label: 'Cost Per Exclusive Lead', value: '$105.00' },
      { label: 'Installed Systems', value: '22 Home Systems' },
    ],
    clientQuote: {
      quote:
        'Having 100% exclusive leads changes everything. Our closing rate jumped dramatically because we are the only solar company calling.',
      author: 'Samantha Lee',
      title: 'Sales Director, California Solar & Electric Inc.',
    },
  },
];

export type Testimonial = {
  quote: string;
  name: string;
  role: string;
  rating: string;
  platform: string;
  score: number;
};

export const testimonials: Testimonial[] = [
  {
    quote:
      'Working with Local Lead Engine was super helpful. He did an amazing job at reviewing my website, making corrections, providing marketing materials, and managing my advertisements.',
    name: 'Jose P.',
    role: 'Business Owner',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 98,
  },
  {
    quote:
      "I highly recommend his team. He's helped me grow my business through his expertise on Google Ads and strategic SEO recommendations.",
    name: 'Kristin P.',
    role: 'CEO',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 97,
  },
  {
    quote:
      'He is an asset that any company should seriously use if they need marketing. His expertise, insight, and creativeness blew us away.',
    name: 'Steven H.',
    role: 'Business Owner',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 99,
  },
  {
    quote:
      'A pleasure to work with. Creative tech is usually a pain to deal with, but he was super easy to collaborate with and consistently met all deadlines.',
    name: 'Robert M.',
    role: 'CEO',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 96,
  },
  {
    quote:
      'He really goes the extra mile and is highly knowledgeable in web design, local marketing, and customer relations.',
    name: 'Charles G.',
    role: 'Business Owner',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 98,
  },
  {
    quote:
      'They are highly recommended. Their expertise in web design and local SEO is solid, and they helped improve our entire business presence.',
    name: 'Naoki F.',
    role: 'CEO',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 97,
  },
  {
    quote:
      'Local Lead Engine completely turned our campaigns around. Rebuilt our campaigns from the ground up, and the cost per qualified lead dropped significantly.',
    name: 'Timothy B.',
    role: 'Business Owner',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 99,
  },
  {
    quote:
      "They don't just set up advertisements and disappear, they constantly check on lead quality. They are proactive and helpful partners in our growth.",
    name: 'Amanda S.',
    role: 'CEO',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 98,
  },
  {
    quote:
      'Finally, a provider that talks straight business. The cost per booking decreased by over 50% since partnering with Local Lead Engine.',
    name: 'Marcus J.',
    role: 'Business Owner',
    rating: '4.9/5',
    platform: 'Verified Client Review',
    score: 99,
  },
];

export type PlanFeatureRow = {
  name: string;
  starter: boolean;
  growth: boolean;
  scale: boolean;
};

export type Plan = {
  id: string;
  name: string;
  blurb: string;
  featured?: boolean;
};

export const plans: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    blurb: 'Essential search ad management and foundational tracking for local contractors.',
  },
  {
    id: 'growth',
    name: 'Growth',
    blurb: 'Advanced tracking, call attribution, and dashboard reporting for growing contractors.',
    featured: true,
  },
  {
    id: 'scale',
    name: 'Scale',
    blurb: 'Full landing page design, priority support, and complete campaign management.',
  },
];

export const planFeatureRows: PlanFeatureRow[] = [
  { name: 'Google Ads Management', starter: true, growth: true, scale: true },
  { name: 'Google Local Services Ads', starter: false, growth: true, scale: true },
  { name: 'Conversion Tracking Setup', starter: true, growth: true, scale: true },
  { name: 'Google Analytics 4 Setup', starter: true, growth: true, scale: true },
  { name: 'Google Tag Manager Setup', starter: true, growth: true, scale: true },
  { name: 'Automation Setup', starter: true, growth: true, scale: true },
  { name: 'Monthly Reporting', starter: true, growth: true, scale: true },
  { name: 'Landing Page Recommendations', starter: true, growth: true, scale: true },
  { name: 'Landing Page Design', starter: false, growth: false, scale: true },
  { name: 'Offline Conversion Tracking Setup', starter: false, growth: true, scale: true },
  { name: 'Call Tracking Integration', starter: false, growth: true, scale: true },
  { name: 'Looker Studio Dashboard', starter: false, growth: true, scale: true },
  { name: 'A/B Testing', starter: false, growth: true, scale: true },
  { name: 'Priority Support', starter: false, growth: false, scale: true },
];

export type Post = {
  id: string;
  title: string;
  category: string;
  tradeTag?: string;
  date: string;
  day: string;
  month: string;
  author: string;
  authorRole?: string;
  image: string;
  excerpt: string;
  readTime: string;
  keyTakeaways?: string[];
  contentParagraphs?: string[];
  caseStudyLink?: {
    title: string;
    tradeSlug: string;
    metric: string;
  };
};

export const posts: Post[] = [
  {
    id: 'stop-wasting-ad-budget',
    title: 'How Contractors Can Stop Wasting Google Ads Budget on DIYers',
    category: 'Google Ads Strategy',
    tradeTag: 'HVAC & Plumbing',
    date: '12 July 2026',
    day: '12',
    month: 'Jul',
    author: 'Marcus Vance',
    authorRole: 'Head of Paid Search',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=80',
    excerpt:
      'Search terms like "free repair guide", "DIY wiring", and "jobs" drain thousands from contractor ad budgets. Learn how our HVAC case study eliminated 68% of wasted spend.',
    readTime: '6 min read',
    keyTakeaways: [
      'Add 120+ standard negative keywords covering DIY, job seekers, and wholesale parts queries.',
      'Use Exact Match search keywords for high-intent replacement terms like "emergency HVAC replacement near me".',
      'Set up audience exclusions for visitors who spend less than 10 seconds on site.'
    ],
    contentParagraphs: [
      'When contractors inspect their search query reports inside Google Ads, they are often shocked to discover up to 40% of click budget is squandered on homeowner DIY queries like "how to fix AC compressor capacitor" or "HVAC hiring apprentice".',
      'By implementing exact match campaign architecture alongside our pre-built 120-term negative keyword list, contractor accounts immediately recover thousands in ad spend that can be reallocated directly to emergency service calls.',
      'In our NC Heating & Air case study, this single negative keyword overhaul reduced cost per acquisition from $142 down to $38 per booked job in less than 30 days.'
    ],
    caseStudyLink: {
      title: 'NC Heating & Air',
      tradeSlug: 'hvac',
      metric: '+310% Booked Jobs'
    }
  },
  {
    id: 'search-vs-lsa',
    title: 'Google Search Ads vs. LSA: Which Generates Cheaper Calls?',
    category: 'LSA Insights',
    tradeTag: 'Roofing & Exterior',
    date: '28 June 2026',
    day: '28',
    month: 'Jun',
    author: 'Sarah Jenkins',
    authorRole: 'LSA Specialist',
    image: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?auto=format&fit=crop&w=1200&q=80',
    excerpt:
      'Local Services Ads offer pay-per-call leads, while Search Ads allow custom landing pages. Here is how our Paragon Roofing case study combined both to book 38 full roof replacements in Q2.',
    readTime: '5 min read',
    keyTakeaways: [
      'LSA shines for immediate, emergency call generation with built-in Google Guaranteed badge trust.',
      'Search Ads win on high-ticket custom jobs where dedicated landing pages communicate value.',
      'Combining LSA + Search Ads captures 65% of top-of-page real estate on mobile devices.'
    ],
    contentParagraphs: [
      'Contractors often treat Google Search Ads and Google Local Services Ads (LSA) as competing channels. In reality, market-leading contractor businesses operate both in tandem to dominate top-of-page search results.',
      'LSA provides pay-per-call accountability with direct dispute capabilities for spam leads, while Search Ads allow custom high-converting landing pages tailored to high-ticket storm damage and full roof replacements.',
      'Our Paragon Roofing campaign deployed this dual strategy, capturing 38 full roof replacements in Q2 while holding average cost per qualified lead to just $42.'
    ],
    caseStudyLink: {
      title: 'Paragon Roofing',
      tradeSlug: 'roofing',
      metric: '38 Full Roof Jobs'
    }
  },
  {
    id: 'contractor-landing-page-guide',
    title: 'The Anatomy of a Contractor Landing Page That Converts at 25%+',
    category: 'Conversion Optimization',
    tradeTag: 'Home Remodeling',
    date: '15 June 2026',
    day: '15',
    month: 'Jun',
    author: 'Dave Kowalski',
    authorRole: 'CRO & UI Strategist',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
    excerpt:
      'Most contractor websites fail because they look like generic brochure sites. Learn the 7 layout triggers that helped Home Repair Service land 46 high-ticket consultations.',
    readTime: '8 min read',
    keyTakeaways: [
      'Sticky click-to-call mobile header accessible at all scroll positions.',
      'Above-the-fold social proof badges (Google 4.9★, Licensed & Insured, Financing Available).',
      '3-step estimate request form asking for project zip code first before contact info.'
    ],
    contentParagraphs: [
      'Sending paid traffic to a standard homepage is the #1 reason contractor ad campaigns fail. A traditional homepage forces visitors to hunt through navigation menus, resulting in bounce rates over 80%.',
      'High-converting contractor landing pages focus strictly on single-action conversion: booking a call or submitting an estimate form. Every element above the fold reinforces immediate trust, local licensing, and recent job photos.',
      'By implementing this dedicated landing page framework for Home Repair Service, lead conversion jumped from 6.2% to 28.4%, yielding 46 new design-build consultation bookings.'
    ],
    caseStudyLink: {
      title: 'Home Repair Service',
      tradeSlug: 'remodeling',
      metric: '28.4% Conversion Rate'
    }
  },
  {
    id: 'disputing-invalid-lsa-leads',
    title: 'How to Dispute Invalid Google LSA Phone Leads for Full Refunds',
    category: 'LSA Insights',
    tradeTag: 'Plumbing & Electrical',
    date: '02 June 2026',
    day: '02',
    month: 'Jun',
    author: 'Marcus Vance',
    authorRole: 'Head of Paid Search',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1200&q=80',
    excerpt:
      'Wrong service area? Out of scope? Spam calls? Step-by-step framework for recovering thousands in refund credits directly from Google Local Services Ads.',
    readTime: '4 min read',
    keyTakeaways: [
      'Dispute invalid leads within 30 days directly inside the LSA lead inbox.',
      'Flag out-of-service area calls, job seekers, and sales solicitations for instant credits.',
      'Train dispatchers to log call reason codes during intake for fast dispute evidence.'
    ],
    contentParagraphs: [
      'Google Local Services Ads charges contractors on a per-call basis, but up to 20% of calls received may be out-of-bounds — including wrong zip codes, job applicants, or services your team does not provide.',
      'Many contractors leave thousands of dollars on the table by failing to audit and dispute these invalid charges within Google’s 30-day window.',
      'Our step-by-step dispute logging protocol recovers an average of $850 - $2,400 monthly in ad credits for client accounts.'
    ],
    caseStudyLink: {
      title: 'Pro Flow Plumbing & Drain',
      tradeSlug: 'plumbing',
      metric: '$2,400 Monthly Saved'
    }
  },
  {
    id: 'servicetitan-jobber-attribution',
    title: 'Tracking Real ROAS: Connecting Google Ads to ServiceTitan & Jobber',
    category: 'Analytics & CRM',
    tradeTag: 'Dispatch & Ops',
    date: '20 May 2026',
    day: '20',
    month: 'May',
    author: 'Sarah Jenkins',
    authorRole: 'Analytics Lead',
    image: 'https://ik.imagekit.io/Localleadengine/Google%20Ads%20Dashboard.png',
    excerpt:
      'Stop judging campaigns by click counts. How to trace a Google search query directly to a completed $8,500 HVAC replacement inside your dispatch software.',
    readTime: '7 min read',
    keyTakeaways: [
      'Pass Google Click Identifier (GCLID) and call tracking data directly into ServiceTitan or Jobber.',
      'Match completed invoice revenue back to exact campaign, keyword, and ad copy.',
      'Optimize ad bidding based on high-ticket job value rather than raw lead volume.'
    ],
    contentParagraphs: [
      'Measuring digital marketing success solely by cost-per-click or lead forms is a recipe for missed revenue. A $30 lead for a minor drain clearing is vastly different from a $50 lead that converts into a $12,000 sewer line replacement.',
      'By establishing dynamic call tracking integration with dispatch tools like ServiceTitan and Jobber, we feed closed invoice revenue data back into Google’s smart bidding algorithm.',
      'This end-to-end attribution allows us to scale high-margin job keywords while cutting spend on low-value service calls.'
    ],
    caseStudyLink: {
      title: 'Local Lead Engine Performance',
      tradeSlug: 'hvac',
      metric: 'Closed ROAS Attribution'
    }
  },
];

export const services = [
  {
    icon: 'Megaphone',
    title: 'Google Ads Management',
    body: 'Hyper-targeted Google Search & Local Services Ads (LSA) campaigns built exclusively for local service contractors to generate qualified estimate requests.',
    points: ['High-intent keyword structuring', 'Negative keyword filtering', 'Local Services Ads (LSA) management'],
  },
  {
    icon: 'BarChart3',
    title: 'Conversion Tracking',
    body: 'Complete phone and form attribution connecting Google Ads to CallRail and CRM to track exact booked jobs and ROAS.',
    points: ['CallRail call recording and DNI setup', 'ServiceTitan and Jobber CRM sync', 'Revenue and ROAS reporting'],
  },
  {
    icon: 'Smartphone',
    title: 'Landing Page Design',
    body: 'High-speed, custom mobile contractor landing pages engineered to convert clicks into high-margin calls and booked estimate requests.',
    points: ['High lead conversion design', 'Mobile-first speed optimization', 'Instant CRM form and call routing'],
  },
] as const;

export const stats = [
  { value: 100, suffix: '+', label: 'Contractor campaigns managed' },
  { value: 100, suffix: 'K+', label: 'Leads generated' },
  { value: 98, suffix: '%', label: 'Contractor retention rate' },
  { value: 8.5, suffix: 'x', label: 'Average Return on Ad Spend (ROAS)' },
] as const;

/* ------------------------------------------------------------------ */
/* Live Results — anonymised rolling contractor campaign benchmark   */
/* ------------------------------------------------------------------ */

export type ResultsTab = {
  id: string;
  label: string;
  icon: string;
  kind: 'line' | 'bar';
  format: 'k' | 'pct' | 'int' | 'decimal';
  title: string;
  headline: string;
  headlineLabel: string;
  delta: string;
  note: string;
  labels: string[];
  series: { name: string; color: string; values: number[]; dashed?: boolean }[];
  kpis: { label: string; value: string; hint: string }[];
};

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export const resultsTabs: ResultsTab[] = [
  {
    id: 'leads',
    label: 'Exclusive Phone Leads',
    icon: 'PhoneCall',
    kind: 'line',
    format: 'int',
    title: 'Monthly qualified phone leads, rolling 12 months',
    headline: '1,420',
    headlineLabel: 'Booked phone leads last month',
    delta: '+340% year on year',
    note: 'Blended across active HVAC, Roofing, Plumbing, and Electrical campaigns. Exclusive inbound calls from ready-to-hire local homeowners.',
    labels: MONTHS,
    series: [
      {
        name: 'Total phone calls',
        color: '#0052FF',
        values: [320, 380, 450, 590, 720, 880, 990, 1120, 1210, 1310, 1380, 1420],
      },
      {
        name: 'Form quote requests',
        color: '#0A0F1D',
        values: [110, 140, 180, 230, 290, 340, 390, 440, 480, 510, 540, 580],
        dashed: true,
      },
    ],
    kpis: [
      { label: 'Call answer rate', value: '94%', hint: 'direct to dispatcher' },
      { label: 'Avg call duration', value: '4m 12s', hint: 'high buying intent' },
      { label: 'Booked job rate', value: '68%', hint: 'from call to dispatch' },
    ],
  },
  {
    id: 'cpl',
    label: 'Cost Per Lead (CPL)',
    icon: 'DollarSign',
    kind: 'bar',
    format: 'int',
    title: 'Average Cost Per Lead ($) by contractor category',
    headline: '$38.50',
    headlineLabel: 'Average CPL across all contractors',
    delta: '-62% vs market average',
    note: 'By combining Google Search Ads with Local Services Ads and tight negative keyword guards, we consistently cut contractor cost per lead by over 60%.',
    labels: ['HVAC', 'Plumbing', 'Roofing', 'Electrical', 'Restoration', 'Landscaping', 'Pest Control', 'Solar'],
    series: [
      {
        name: 'Local Lead Engine CPL',
        color: '#0052FF',
        values: [36, 32, 58, 29, 64, 28, 24, 72],
      },
      {
        name: 'Industry Average CPL',
        color: '#0A0F1D',
        values: [110, 95, 165, 85, 180, 75, 68, 190],
      },
    ],
    kpis: [
      { label: 'HVAC Cost/Lead', value: '$36.00', hint: 'down from $110' },
      { label: 'Roofing Cost/Lead', value: '$58.00', hint: 'down from $165' },
      { label: 'Plumbing Cost/Lead', value: '$32.00', hint: 'down from $95' },
    ],
  },
  {
    id: 'roas',
    label: 'Return on Ad Spend (ROAS)',
    icon: 'TrendingUp',
    kind: 'line',
    format: 'decimal',
    title: 'Monthly Return on Ad Spend (ROAS) multiplier',
    headline: '5.8x',
    headlineLabel: 'Average ROAS across client accounts',
    delta: '$5.80 returned per $1 ad spend',
    note: 'Tracked directly through ServiceTitan and Jobber integrations. Every dollar invested in Google Ads yields measurable booked service revenue.',
    labels: MONTHS,
    series: [
      {
        name: 'Client Account ROAS',
        color: '#0052FF',
        values: [2.1, 2.4, 2.9, 3.4, 3.8, 4.2, 4.6, 5.0, 5.2, 5.5, 5.7, 5.8],
      },
      {
        name: 'Target Threshold',
        color: '#0A0F1D',
        values: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0],
        dashed: true,
      },
    ],
    kpis: [
      { label: 'Monthly ad revenue', value: '$3.2M+', hint: 'tracked in CRM' },
      { label: 'Avg ticket size', value: '$2,450', hint: 'installations & repairs' },
      { label: 'Payback period', value: '< 14 days', hint: 'from ad click to job cash' },
    ],
  },
];

export const processSteps = [
  {
    step: '01',
    title: 'Phase 1 - Audit & Implement',
    body: 'We audit your account, fix tracking, and build the foundation for accurate measurement.',
  },
  {
    step: '02',
    title: 'Phase 2 - Launch',
    body: 'We launch high-intent Google Ads campaigns designed to generate qualified estimate requests.',
  },
  {
    step: '03',
    title: 'Phase 3 - Optimize',
    body: 'We improve lead quality, reduce wasted ad spend, and optimize for booked estimates.',
  },
  {
    step: '04',
    title: 'Phase 4 - Scale',
    body: 'We increase budget strategically, expand winning campaigns, and drive sustainable growth.',
  },
] as const;

export const team = [
  { name: 'Marcus Vance', role: 'Founder & CEO' },
  { name: 'Sarah Jenkins', role: 'Head of Google Ads Strategy' },
  { name: 'Dave Kowalski', role: 'Director of Contractor Growth' },
  { name: 'Priya Raman', role: 'Lead Landing Page Engineer' },
  { name: 'Tomas Lindqvist', role: 'Click Fraud & LSA Specialist' },
  { name: 'Élodie Marchand', role: 'CRM Attribution Specialist' },
] as const;

export const openRoles = [
  { title: 'Senior Google Ads Strategist (Contractor Focus)', type: 'Full time', place: 'Remote / US' },
  { title: 'Contractor Landing Page Designer', type: 'Full time', place: 'Remote' },
  { title: 'Local Services Ads (LSA) Manager', type: 'Full time', place: 'Remote' },
  { title: 'ServiceTitan & CRM Integration Engineer', type: 'Contract', place: 'Remote' },
] as const;

export const faqs = [
  {
    q: 'How can Google Ads management help my business get more inquiries?',
    a: 'Google Ads management helps local service businesses reach people searching for their services on Google. We manage campaigns, keywords, ads, tracking, and budget to help turn relevant searches into calls and form inquiries.',
  },
  {
    q: 'Do I still need Google Ads management if I already run Google Ads?',
    a: 'If you already run Google Ads, management can help review your campaigns, search terms, conversion tracking, budget, and account structure to see where improvements can be made.',
  },
  {
    q: 'What types of businesses does Google Ads management work for?',
    a: 'Google Ads management works well for local service businesses such as roofing, HVAC, home remodeling, window and door, deck and outdoor living, and solar contractors.',
  },
  {
    q: 'Can Google Ads management improve the quality of inquiries I get?',
    a: 'Yes. Google Ads management can focus campaigns on relevant services, locations, keywords, and searches that are more closely related to the work your business provides.',
  },
  {
    q: 'How much does Google Ads management cost?',
    a: 'The cost of Google Ads management depends on the services included, campaign size, number of locations, and amount of work needed to manage the account.',
  },
  {
    q: 'How long does it take to see results from Google Ads?',
    a: 'Some campaigns can start receiving inquiries soon after launch. More time is usually needed to collect enough data to evaluate performance and make informed campaign changes.',
  },
  {
    q: 'Do I need a big budget to get started with Google Ads?',
    a: 'You do not need the same budget as every other business. The right Google Ads budget depends on your service, location, competition, average job value, and business capacity.',
  },
  {
    q: 'Do I need a website for Google Ads?',
    a: 'A good website is important for Google Ads because visitors need a clear place to learn about your service and contact your business. We can review your existing website before recommending changes.',
  },
  {
    q: 'Can you manage my existing Google Ads account?',
    a: 'Yes. We can review your existing Google Ads account and work with the current campaigns, conversion tracking, keywords, ads, and budget.',
  },
  {
    q: 'How do I get started with Google Ads management?',
    a: 'We start by reviewing your business, services, locations, website, current Google Ads account, and conversion tracking. Then we can explain what needs to be done to get started.',
  },
] as const;

export const servicePageFaqs = [
  {
    q: 'How can Google Ads for Local Service Contractors help my business?',
    a: 'Google Ads for Local Service Contractors can put your business in front of people searching for the services you provide in your service area.',
  },
  {
    q: 'What types of contractors can use Google Ads?',
    a: 'Google Ads can work for roofing contractors, HVAC contractors, remodeling contractors, window and door contractors, deck contractors, outdoor living contractors, solar contractors, and other local service businesses.',
  },
  {
    q: 'Do I still need Google Ads management if I already run Google Ads?',
    a: 'If your campaigns are already running, Google Ads management can help review keywords, search terms, locations, ads, conversion tracking, bidding, and budget use.',
  },
  {
    q: 'Can Google Ads for Local Service Contractors improve the quality of inquiries?',
    a: 'Yes. Campaigns can focus on relevant services, locations, and search terms instead of sending the budget toward searches that are not useful for your business.',
  },
  {
    q: 'How do Google Local Services Ads work for contractors?',
    a: 'Google Local Services Ads can help eligible contractors appear when people search for local services. Customers can contact the business through available lead options such as calls, messages, and bookings where supported.',
  },
  {
    q: 'What is the difference between Google Ads and Local Services Ads?',
    a: 'Google Ads and Local Services Ads are different advertising options. Standard Google Ads can send people to your website, while Local Services Ads are built around local service inquiries and lead generation.',
  },
  {
    q: 'How much do Google Local Services Ads cost?',
    a: 'With Local Services Ads, you pay for valid leads rather than every click. Lead prices can vary based on factors such as location, job type, lead type, and bidding settings.',
  },
  {
    q: 'Do reviews matter for Google Local Services Ads?',
    a: 'Yes. Your rating and number of reviews can affect how your business is ranked in Local Services Ads.',
  },
  {
    q: 'Can you help manage Google Local Services Ads?',
    a: 'Yes. We can review your Local Services Ads setup, business profile, service areas, job types, budget, leads, reviews, and performance alongside your standard Google Ads campaigns.',
  },
  {
    q: 'How do I get started with Google Ads and Local Services Ads?',
    a: 'We first review your services, locations, website, Google Ads account, Local Services Ads account if you have one, tracking, and budget. From there, we can recommend the right setup for your business.',
  },
] as const;

export const footerColumns = [
  {
    title: 'Categories',
    links: [
      { label: 'Roofing Contractors', href: '/contractors/google-ads-for-roofing-contractors' },
      { label: 'HVAC Contractors', href: '/contractors/google-ads-for-hvac-contractors' },
      { label: 'Home Remodeling Contractors', href: '/contractors/google-ads-for-remodeling-contractors' },
      { label: 'Window & Door Contractors', href: '/contractors/google-ads-for-window-door-contractors' },
      { label: 'Deck & Outdoor Living', href: '/contractors/google-ads-for-deck-outdoor-living-contractors' },
      { label: 'Solar Contractors', href: '/contractors/google-ads-for-solar-contractors' },
    ],
  },
  {
    title: 'Services',
    links: [
      { label: 'Google Ads Management', href: '/google-ads-for-local-service-contractors' },
      { label: 'Conversion Tracking', href: '/google-ads-for-local-service-contractors' },
      { label: 'Landing Page Design', href: '/google-ads-for-local-service-contractors' },
    ],
  },
  {
    title: 'Company',
    links: [
      { label: 'About Us', href: '/about' },
      { label: 'Case Studies', href: '/case-studies' },
      { label: 'Blogs', href: '/blog' },
      { label: 'FAQs', href: '/faqs' },
      { label: 'Book Strategy Call', href: '/strategy-call' },
      { label: 'Privacy Policy', href: '/privacy' },
      { label: 'Terms of Service', href: '/terms' },
    ],
  },
] as const;

export const contactDetails = {
  address: [] as string[],
  email: 'localleadengine.io@gmail.com',
  phone: '+880 1762595245',
  hours: 'Mon – Fri, 7:00 AM – 6:00 PM EST',
};

export const socialLinks = {
  linkedin: 'https://www.linkedin.com/in/abu-salah/',
  instagram: 'https://www.instagram.com/local_lead_engine/',
  facebook: 'https://www.facebook.com/localleadengine.io',
};
